export const ENTITY_TYPE_TOPNAV_LEFT = 'ENTITY_TYPE_TOPNAV_LEFT';
export const ENTITY_TYPE_TOPNAV_RIGHT = 'ENTITY_TYPE_TOPNAV_RIGHT';
export const ENTITY_TYPE_SIDENAV = 'ENTITY_TYPE_SIDENAV';
export const ENTITY_TYPE_GLOBALS = 'ENTITY_TYPE_GLOBALS';

export const ENTITY_TYPE_DATA_SOURCE = 'ENTITY_TYPE_DATA_SOURCE';
export const ENTITY_TYPE_TABLE = 'ENTITY_TYPE_TABLE';
export const ENTITY_TYPE_QUERY_RESULT = 'ENTITY_TYPE_QUERY_RESULT';
export const ENTITY_TYPE_GRID = 'ENTITY_TYPE_GRID';

export const CONTAINER_MODE_ITEM = 'CONTAINER_MODE_ITEM';
export const CONTAINER_MODE_FORM = 'CONTAINER_MODE_FORM';
export const CONTAINER_MODE_LIST = 'CONTAINER_MODE_LIST';

export const STORE_LIST_INIT = 'STORE_LIST_INIT';
export const STORE_LIST_FETCH_INIT = 'STORE_LIST_FETCH_INIT';
export const STORE_LIST_FETCH_SUCCESS = 'STORE_LIST_FETCH_SUCCESS';
export const STORE_LIST_FETCH_ERROR = 'STORE_LIST_FETCH_ERROR';
export const STORE_LIST_UPDATE = 'STORE_LIST_UPDATE';