export const ENTITY_TYPE_TOPNAV_LEFT = 'ENTITY_TYPE_TOPNAV_LEFT';
export const ENTITY_TYPE_TOPNAV_RIGHT = 'ENTITY_TYPE_TOPNAV_RIGHT';
export const ENTITY_TYPE_SIDENAV = 'ENTITY_TYPE_SIDENAV';
export const ENTITY_TYPE_GLOBALS = 'ENTITY_TYPE_GLOBALS';

// Meta information about currently selected grid
export const ENTITY_TYPE_GRID = 'ENTITY_TYPE_GRID';

export const ENTITY_TYPE_DATA_SOURCE = 'ENTITY_TYPE_DATA_SOURCE';
export const ENTITY_TYPE_TABLE = 'ENTITY_TYPE_TABLE';

export const ENTITY_TYPE_DATA = 'ENTITY_TYPE_DATA';
export const ENTITY_TYPE_DATA_RESULT = 'ENTITY_TYPE_DATA_RESULT';
export const ENTITY_TYPE_DATA_HEAD = 'ENTITY_TYPE_DATA_HEAD';
export const ENTITY_TYPE_DATA_ORDER = 'ENTITY_TYPE_DATA_ORDER';


/*
Deal with list and item reducers
*/
export const STORE_LIST_INIT = 'STORE_LIST_INIT';
export const STORE_LIST_FETCH_INIT = 'STORE_LIST_FETCH_INIT';
export const STORE_LIST_FETCH_SUCCESS = 'STORE_LIST_FETCH_SUCCESS';
export const STORE_LIST_FETCH_ERROR = 'STORE_LIST_FETCH_ERROR';
export const STORE_LIST_MERGE = 'STORE_LIST_MERGE';
export const STORE_LIST_SELECT_ITEM = 'STORE_LIST_SELECT_ITEM';
export const STORE_LIST_DESTROY = 'STORE_LIST_DESTROY';

export const STORE_ITEM_INIT = 'STORE_ITEM_INIT';
export const STORE_ITEM_FETCH_INIT = 'STORE_ITEM_FETCH_INIT';
export const STORE_ITEM_FETCH_SUCCESS = 'STORE_ITEM_FETCH_SUCCESS';
export const STORE_ITEM_FETCH_ERROR = 'STORE_ITEM_FETCH_ERROR';
export const STORE_ITEM_UPDATE = 'STORE_ITEM_UPDATE';
export const STORE_ITEM_DESTROY = 'STORE_ITEM_DESTROY';