export const ENTITY_TYPE_TOPNAV_LEFT = 'ENTITY_TYPE_TOPNAV_LEFT';
export const ENTITY_TYPE_TOPNAV_RIGHT = 'ENTITY_TYPE_TOPNAV_RIGHT';
export const ENTITY_TYPE_SIDENAV = 'ENTITY_TYPE_SIDENAV';
export const ENTITY_TYPE_GLOBALS = 'ENTITY_TYPE_GLOBALS';

export const ENTITY_TYPE_DATA_SOURCE = 'ENTITY_TYPE_DATA_SOURCE';
export const ENTITY_TYPE_TABLE = 'ENTITY_TYPE_TABLE';

export const ENTITY_TYPE_DATA = 'ENTITY_TYPE_DATA';
export const ENTITY_TYPE_DATA_RESULT = 'ENTITY_TYPE_DATA_RESULT';
export const ENTITY_TYPE_DATA_HEAD = 'ENTITY_TYPE_DATA_HEAD';
export const ENTITY_TYPE_DATA_ORDER = 'ENTITY_TYPE_DATA_ORDER';

export const CONTAINER_MODE_ITEM = 'CONTAINER_MODE_ITEM';
export const CONTAINER_MODE_FORM = 'CONTAINER_MODE_FORM';
export const CONTAINER_MODE_LIST = 'CONTAINER_MODE_LIST';

export const STORE_LIST_INIT = 'STORE_LIST_INIT';
export const STORE_LIST_FETCH_INIT = 'STORE_LIST_FETCH_INIT';
export const STORE_LIST_FETCH_SUCCESS = 'STORE_LIST_FETCH_SUCCESS';
export const STORE_LIST_FETCH_ERROR = 'STORE_LIST_FETCH_ERROR';
export const STORE_LIST_MERGE = 'STORE_LIST_MERGE';
export const STORE_LIST_SELECT_ITEM = 'STORE_LIST_SELECT_ITEM';

export const CONTAINER_MIXIN_FORM = 'CONTAINER_MIXIN_FORM';
export const CONTAINER_MIXIN_GET_LIST = 'CONTAINER_MIXIN_GET_LIST';
export const CONTAINER_MIXIN_GET_ITEM = 'CONTAINER_MIXIN_GET_ITEM';
export const CONTAINER_MIXIN_ROUTER = 'CONTAINER_MIXIN_ROUTER';